# Nombre del workflow (opcional, pero recomendado)
name: Mi Primer Workflow

# Evento(s) que disparan el workflow
on: 
  push:
  pull_request:

# Trabajos que se ejecutarán
jobs:
  mi_primer_job: # ID del job
    name: Saludar # Nombre legible del job (opcional)
    runs-on: ubuntu-latest # Tipo de runner a usar
    steps:
      - name: Paso 1 - Imprimir saludo
        run: echo "¡Hola Mundo desde GitHub Actions!"
