name: Despliegue Manual
on:
  workflow_dispatch:
    inputs: # Opcional: define entradas que el usuario puede proporcionar
      environment:
        description: 'Entorno de despliegue'
        required: true
        default: 'staging'
        type: choice # Tipos: string, choice, boolean, environment
        options:
          - staging
          - production
      logLevel:
        description: 'Nivel de Log'
        required: false
        default: 'info'
        type: string
