name: Deploy to Server
jobs:
  first_jobs:
    runs-on: ubuntu-latest
    outputs:
     salida: ${{ steps.step_1.outputs.my_variable }}
    steps:
      - name: Working DIR
        id: step_1
        run: echo "my-variable=Hola Mundo" >> $GITHUB_OUTPUT 

      - name: obteenr comando
        run: echo "${{ steps.step_1.outputs.my_variable }}"
  seconds_jobs:
    needs: first_jobs
    runs-on: ubuntu-latest

    env:
      SALIDA: ${{ needs.first_job.outputs.salida}}
    steps:
      - name: Hola mundo
        run: echo "$SALIDA"     
